/*
* Copyright (c) 2016 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : POC_RX71M.c
*  Description  : Main Program
*  Creation Date: 2026-10-03
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "FreeRTOS.h"
#include "task.h"

extern void board_app_run(void);

void main_task(void *pvParameters);

void main_task(void *pvParameters)
{
    (void) pvParameters;
    board_app_run();
    vTaskDelete(NULL);
}