/*
* Copyright (c) 2016 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : POC_RX71M.c
*  Description  : FreeRTOS 主任务。真正的板级循环在 board_app_run()。
*  Creation Date: 2026-10-03
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "FreeRTOS.h"
#include "task.h"

/* 在 board_resources.cpp 里实现，C 链接。 */
extern void board_app_run(void);

/* 先声明再定义，满足 -Wmissing-declarations。 */
void main_task(void *pvParameters);

/* FreeRTOS 启动后跑的唯一应用任务。 */
void main_task(void *pvParameters)
{
    (void) pvParameters; /* 创建任务时没传参数。 */
    board_app_run();     /* 初始化外设并循环，正常不会返回。 */
    vTaskDelete(NULL);   /* 若上面返回，删掉自己，避免落到调度器外面。 */
}
